In [1]:
import pandas as pd

In [17]:
hehe=pd.Series([1,2,4,5,7,8],index=["pro",'isf','me','bruh','23',64])
pd.DataFrame(hehe)
hehe.index
hehe.columns=['rank']
hehe.columns
pd.DataFrame(hehe)

      0
pro   1
isf   2
me    4
bruh  5
23    7
64    8

In [66]:
df.loc[0:2, ["Name", "Age"]] # Rows 0 to 2, selected columns
df.iloc[0:2, 0:2]
df[(df["Name"] == "Bob") | (df["Age"] < 30)]
df.query("`Name` == 'Alice'")
age_limit = 30
df.query("Age > @age_limit")

      Name  Age
2  Charlie   35

In [98]:
new=pd.read_csv("data22.csv")
y=pd.DataFrame(new)

In [99]:
data = [["Alice", 25],["Bob",30],["Charlie", 35]]
pd.DataFrame(data,columns=['name','age'])

data = {
"Name": ["Alice", "Bob", "Charlie","Bob"],
"Age": [25,25,35,25]
}
df = pd.DataFrame(data)
df
df.head(2)
df.info()
df.describe()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

(4, 2)

In [100]:
y.isnull().sum()
y.dropna()
y.fillna('Null')
y["Age"].fillna(y["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [104]:
#for working with duplicates
y.duplicated()
y.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  12-02-2026
1  Charlie   NaN        Delhi      M    charlie@example  13-02-2026
2      Bob  30.0  Los Angeles      M                NaN  14-02-2026
4    David  22.0       Mumbai      M  david@example.com  16-02-2026
5      NaN  28.0        Delhi      F     eve@domain.com  17-02-2026

In [107]:
y["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2                     NaN
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [115]:
y2=y.dropna().copy()
y2
y2.info()
y2["like"]=y2["Gender"].apply(lambda x:"Yes" if x=='F' else "No")
y2

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      object
 1   Age        4 non-null      float64
 2   City       4 non-null      object
 3   Gender     4 non-null      object
 4   Email      4 non-null      object
 5   Join Date  4 non-null      object
dtypes: float64(1), object(5)
memory usage: 224.0+ bytes

    Name   Age      City Gender              Email   Join Date like
0  Alice  25.0  New York      F  alice@example.com  12-02-2026  Yes
4  David  22.0    Mumbai      M  david@example.com  16-02-2026   No
6  Alice  25.0  New York      F  alice@example.com  12-02-2026  Yes
7  Alice  25.0  New York      F  alice@example.com  12-02-2026  Yes

In [118]:
y2["Gender"].map({"F":"Queen","M":"ohhh"})

    Name   Age      City Gender              Email   Join Date like
0  Alice  25.0  New York      F  alice@example.com  12-02-2026  Yes
4  David  22.0    Mumbai      M  david@example.com  16-02-2026   No
6  Alice  25.0  New York      F  alice@example.com  12-02-2026  Yes
7  Alice  25.0  New York      F  alice@example.com  12-02-2026  Yes