In [1]:
import pandas as pd

In [6]:
y=pd.read_csv("data22.csv")
y2=pd.DataFrame(y)

In [12]:
y2.sort_values("Age",ascending=True)

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  16-02-2026
0    Alice  25.0     New York      F  alice@example.com  12-02-2026
6    Alice  25.0     New York      F  alice@example.com  12-02-2026
7    Alice  25.0     New York      F  alice@example.com  12-02-2026
5      NaN  28.0        Delhi      F     eve@domain.com  17-02-2026
2      Bob  30.0  Los Angeles      M                NaN  14-02-2026
1  Charlie   NaN        Delhi      M    charlie@example  13-02-2026
3  Charlie   NaN        Delhi      M    charlie@example  13-02-2026
8  Charlie   NaN        Delhi      M    charlie@example  13-02-2026

In [14]:
y2.sort_values(["Age","Join Date"],ascending=True)

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  16-02-2026
0    Alice  25.0     New York      F  alice@example.com  12-02-2026
6    Alice  25.0     New York      F  alice@example.com  12-02-2026
7    Alice  25.0     New York      F  alice@example.com  12-02-2026
5      NaN  28.0        Delhi      F     eve@domain.com  17-02-2026
2      Bob  30.0  Los Angeles      M                NaN  14-02-2026
1  Charlie   NaN        Delhi      M    charlie@example  13-02-2026
3  Charlie   NaN        Delhi      M    charlie@example  13-02-2026
8  Charlie   NaN        Delhi      M    charlie@example  13-02-2026